spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mocker
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    cache-period: 0
